---
kind: pipeline
type: docker
name: default
steps:
  - name: publish
    image: node:lts-alpine
    privileged: true
    environment:
      PERSONAL_ACCESS_TOKEN:
        from_secret: PERSONAL_ACCESS_TOKEN
    commands:
      - apk add libsecret
      - npm install -g @vscode/vsce
      - npm install typescript -g
      - npm install
      - vsce package
      - vsce publish -p ${PERSONAL_ACCESS_TOKEN}
    when:
      branch:
        - main
